# Generated by Django 4.2.7 on 2023-11-17 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_skills', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vacancies', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics', models.IntegerField()),
                ('date_recording', models.DateTimeField(auto_now_add=True)),
                ('key_skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesapp.skill')),
                ('vacancies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesapp.vacancy')),
            ],
            options={
                'unique_together': {('vacancies', 'key_skills')},
            },
        ),
    ]
