# Generated by Django 4.2.7 on 2023-11-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacancyskill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='skill',
            name='vacancies',
            field=models.ManyToManyField(through='tablesapp.VacancySkill', to='tablesapp.vacancy'),
        ),
        migrations.AddConstraint(
            model_name='vacancyskill',
            constraint=models.UniqueConstraint(fields=('vacancies', 'key_skills'), name='unique_vacancy_skill'),
        ),
    ]
